---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - echo foo

notifications:
  campfire:
    secure: "JJezWGD9KJY/LC2aznI3Zyohy31VTIhcTKX7RWR4C/C8YKbW9kZv3xV6Vn11\nSHxJTeZo6st2Bpv6tjlWZ+HCR09kyCNavIChedla3+oHOiuL0D4gSo+gkTNW\nUKYZz9mcQUd9RoQpTeyxvdvX+l7z62/7JwFA7txHOqxbTS8jrjc="

before_deploy:
  - ember build --env production

deploy:
  provider: s3
  access_key_id: $MAINTENANCE_S3_ACCESS_KEY_ID 
  secret_access_key: $MAINTENANCE_S3_SECRET_ACCESS_KEY 
  bucket: drogus-travis-maintenance-test
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  on:
    branch: maintenance-s3-deploy
